name: 'Architect Build'
description: 'Builds and Architect app'
inputs:
  use_lock_file:
    required: false
    default: true
  node-version:
    required: false
    default: 14
runs:
  using: "composite"
  steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Env
        shell: bash
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Git ref:    ${{ github.ref }}"
          echo "GH actor:   ${{ github.actor }}"
          echo "SHA:        ${{ github.sha }}"
          VER=`node --version`; echo "Node ver:   $VER"
          VER=`npm --version`; echo "npm ver:    $VER"

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: ${{ inputs.use_lock_file }}

      - name: Install Architect
        shell: bash
        run: npm install @architect/architect

      - name: Vendor dist files
        shell: bash
        run: npm run dist --if-present

      - name: Hydrate
        shell: bash
        run: npx arc hydrate

      - name: Test
        shell: bash
        run: npm test
